team_performance_manager_etl:
  target: production
  outputs:
    production:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      dbname: "{{ env_var('DB_NAME') }}" # or database instead of dbname
      schema: "{{ env_var('DBT_SCHEMA') }}"
      connect_timeout: 10 # default 10 seconds
      # threads: [optional, 1 or more]
      # [keepalives_idle](#keepalives_idle): 0 # default 0, indicating the system default. See below
      # [retries](#retries): 1  # default 1 retry on error/timeout when opening connections
      # [search_path](#search_path): [optional, override the default postgres search_path]
      # [role](#role): [optional, set the role dbt assumes when executing queries]
      # [sslmode](#sslmode): [optional, set the sslmode used to connect to the database]
      # [sslcert](#sslcert): [optional, set the sslcert to control the certifcate file location]
      # [sslkey](#sslkey): [optional, set the sslkey to control the location of the private key]
      # [sslrootcert](#sslrootcert): [optional, set the sslrootcert config value to a new file path in order to customize the file location that contain root certificates]
  