version: 2

models:
  - name: filtered_repositories
    description: "Table containing GitHub repositories filtered by the 'trades-org' organization."
  
  - name: filtered_commits
    description: "Table containing GitHub commits filtered by repositories in the 'trades-org' organization."

  - name: filtered_prs
    description: "Table containing GitHub pull requests (PRs) filtered by the 'trades-org' user ID."
  
  - name: filtered_issues
    description: "Table containing GitHub issues filtered by repositories in the 'trades-org' organization."