version: 2

models:
  - name: issues_activities_map
    description: "Table containing activities made by members related to Linear tasks (issues)"
    columns:
      - name: member_id
        description: "The email address of the organization member associated with the activity"
        data_tests:
          - not_null
          - relationship:
              to: ref("team_members_map")
              field: id

      - name: date
        description: "The date when the activity took place"
        data_tests:
          - not_null

      - name: issue_id
        description: "The unique identifier of the task associated with the activity"
        data_tests:
          - not_null
          - relationship:
              to: ref("filtered_issues")
              field: id

      - name: activity
        description: "Details of the activities, stored as an array of JSON, which may include information such as action type, description and others. For more details visit: https://miro.com/app/board/uXjVK1WQa6Y=/?moveToWidget=3458764604060004619&cot=14"
        data_tests:
          - not_null