version: 2

models:
  - name: team_members_map
    description: "Table containing information about trades.org members, including their emails, Linear and GitHub details."
    columns:
      - name: id
        description: "Primary Key (PK) for this table, representing the member's organizational email address."
        data_tests:
          - unique
          - not_null

      - name: first_name
        description: "The first name of the member"
        data_tests:
          - not_null

      - name: last_name
        description: "The last name of the member"
        data_tests:
          - not_null

      - name: display_name
        description: "The display name of the member"
        data_tests:
          - not_null

      - name: metadata
        description: "The metadata of the member. It includes data from Linear, Github, Slack and email addresses"
        data_tests:
          - not_null

